# Site settings
title: Federico Astolfi
description: PhD student in Quantum Computing at CESQ, University of Strasbourg
baseurl: "" # Leave empty for username.github.io
url: "https://federicoastolfi.github.io"

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Social links
github_username: FedericoAstolfi
linkedin_username: federico-astolfi-450250216
